#server:
#  error:
#    include-message: always
spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:30000/instantai
    username: postgres
    password: postgres

  flyway:
    enabled: false
    url: jdbc:postgresql://localhost:30000/instantai
    user: postgres
    password: postgres
    locations: classpath:db
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak.instant.ai/realms/master/protocol/openid-connect/certs
      client:
        registration:
          keycloak:
            client-id: instantai
            client-secret: c0VqkTiSUIMhSn8D4tlgKHC5UZAGZOjY
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid, profile, email
            client-name: litetest
            provider: keycloak
        provider:
          keycloak:
            issuer-uri: http://keycloak.instant.ai/realms/master
            authorization-uri: http://keycloak.instant.ai/realms/master/protocol/openid-connect/auth
            token-uri: http://keycloak.instant.ai/realms/master/protocol/openid-connect/token
            user-info-uri: http://keycloak.instant.ai/realms/master/protocol/openid-connect/userinfo